#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export DEFAULT_USER="jcostamagna"
export EDITOR='nvim'
export VISUAL='nvim'
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
#export WECHALLUSER='bbanakaffalatta'
#export WECHALLTOKEN='6A704-51FE6-63AA7-531AC-B1B83-65B7B'
#export PATH="$PATH:/usr/local/go/bin"
#export GOPATH="$HOME/go"
#export PATH="$PATH:$(go env GOPATH)/bin"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"

PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/jcostamagna/.local/bin
