#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
source "$HOME/.config/zprezto/init.zsh"

# Customize to your needs...
function add_yubikey() {
# sudo apt install pcscd scdaemon gnupg2 pcsc-tools
    export GPG_TTY="$(tty)"
    export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
    gpgconf --launch gpg-agent
    ssh-add -D
    gpg-connect-agent updatestartuptty /bye
	gpgconf --launch gpg-agent
}
add_yubikey
alias ipa='ip --brief --color address'
alias vi="nvim"
alias git="hub"
alias r="ranger"
alias listpackage="pacman -Qq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'"
