#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
source "$HOME/.config/zprezto/init.zsh"

# Customize to your needs...
function add_yubikey() {
# sudo apt install pcscd scdaemon gnupg2 pcsc-tools
    export GPG_TTY="$(tty)"
    export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
    gpgconf --launch gpg-agent
    ssh-add -D
    gpg-connect-agent updatestartuptty /bye
	gpgconf --launch gpg-agent
}
alias ipa='ip --brief --color address'
alias r="ranger"
alias rm='trash-put'
source /home/jcostamagna/.config/broot/launcher/bash/br
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
